import { createFileRoute } from '@tanstack/react-router';
import { LegalPage, LegalSection } from '@/components/LegalPage';

export const Route = createFileRoute('/privacy')({
  component: PrivacyPage,
  head: () => ({ meta: [{ title: 'Privacy Policy — Sanyog' }] }),
});

function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="5 September 2026">
      <LegalSection heading="Who we are">
        <p style={{ margin: 0 }}>
          Sanyog is an innovation-procurement platform that connects government departments with recognised
          startups — from problem statement to sandbox pilot to scale-up. It is built at the IIT Kharagpur
          Innovation Cell for Smart India Hackathon 2026 (Problem Statement 26136). This policy explains what
          information we collect and how we use it.
        </p>
      </LegalSection>

      <LegalSection heading="Information we collect">
        <ul style={{ margin: 0, paddingLeft: 20 }}>
          <li><strong style={{ color: 'rgba(255,255,255,0.85)' }}>Account information.</strong> Your name and email address. If you sign in with Google, we receive your Google account name, email address and profile photo. If you sign in with a one-time code (OTP), we use only your email address.</li>
          <li><strong style={{ color: 'rgba(255,255,255,0.85)' }}>Content you submit.</strong> Startup or department profiles, challenge statements, applications, evaluation scores and notes, and documents you upload to the Solution Vault.</li>
          <li><strong style={{ color: 'rgba(255,255,255,0.85)' }}>Technical information.</strong> Standard server logs (such as IP address and browser type) generated by our hosting provider to keep the service secure and running.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="How we use Google user data">
        <p style={{ margin: '0 0 8px' }}>
          When you choose &ldquo;Sign in with Google&rdquo;, we request only your basic profile: name, email
          address and profile photo (the <em>openid</em>, <em>email</em> and <em>profile</em> scopes). We use this
          solely to create and sign you into your Sanyog account and to show your identity inside the platform.
        </p>
        <p style={{ margin: 0 }}>
          We do not request access to your Gmail, Drive, Contacts or any other Google data. We never sell Google
          user data, never use it for advertising, and never share it with third parties except the service
          providers listed below that operate the platform on our behalf.
        </p>
      </LegalSection>

      <LegalSection heading="How we use your information">
        <ul style={{ margin: 0, paddingLeft: 20 }}>
          <li>To create your account and authenticate you (including emailing you one-time sign-in codes).</li>
          <li>To run the procurement workflow: publishing challenges, screening eligibility, panel evaluation, sandbox pilots, milestone payments, validation and scale-up.</li>
          <li>To deliver notifications you trigger, such as a department&rsquo;s message reaching a startup founder.</li>
          <li>To generate advisory scores (FitScore™) on content you choose to submit. These scores assist users; procurement decisions on the platform are made by people, not AI.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Who we share it with">
        <p style={{ margin: '0 0 8px' }}>We do not sell your personal information. It is processed only by the service providers that run the platform:</p>
        <ul style={{ margin: 0, paddingLeft: 20 }}>
          <li>Google — sign-in (OAuth)</li>
          <li>Cloudflare — application hosting</li>
          <li>Supabase — database and file storage</li>
          <li>Resend — transactional email delivery</li>
          <li>Groq — AI processing of content you submit for scoring</li>
        </ul>
        <p style={{ margin: '8px 0 0' }}>
          Within the platform, information is visible according to its purpose — for example, a department
          reviewing a challenge can see the applications submitted to that challenge, and confidential documents
          are visible only to users you approve.
        </p>
      </LegalSection>

      <LegalSection heading="Data retention and deletion">
        <p style={{ margin: 0 }}>
          You can delete your account at any time from the account menu inside the platform; this removes your
          user record. To request removal of other content associated with you, email us and we will action it
          within a reasonable time.
        </p>
      </LegalSection>

      <LegalSection heading="Security">
        <p style={{ margin: 0 }}>
          All traffic is encrypted in transit (HTTPS). Data is stored in an access-controlled database with
          row-level security, and confidential documents are gated behind explicit access approval and an audit log.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to this policy">
        <p style={{ margin: 0 }}>
          If we make material changes to this policy, we will update this page and revise the &ldquo;last
          updated&rdquo; date above.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
